### PR TITLE
Better if-clause when creating directory

### PR DESCRIPTION
**Pull request by ocefpaf**
Ping @pelson.

### CODE REVIEW

**Comment by pelson** [comment]
Ouch, on OSX:

```
 cp /Users/travis/miniconda3/conda-bld/work/lib/mpl_toolkits/basemap/data/countries_i.dat /Users/travis/miniconda3/conda-bld/work/lib/mpl_toolkits/basemap/data/countriesmeta_i.dat /Users/travis/miniconda3/conda-bld/work/lib/mpl_toolkits/basemap/data/gshhs_i.dat /Users/travis/miniconda3/conda-bld/work/lib/mpl_toolkits/basemap/data/gshhsmeta_i.dat /Users/travis/miniconda3/conda-bld/work/lib/mpl_toolkits/basemap/data/rivers_i.dat /Users/travis/miniconda3/conda-bld/work/lib/mpl_toolkits/basemap/data/riversmeta_i.dat /Users/travis/miniconda3/conda-bld/work/lib/mpl_toolkits/basemap/data/states_i.dat /Users/travis/miniconda3/conda-bld/work/lib/mpl_toolkits/basemap/data/statesmeta_i.dat /Users/travis/miniconda3/envs/_build/share/basemap
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
Command failed: /bin/bash -x -e /Users/travis/build/conda-forge/basemap-data-hires-feedstock/recipe/build.sh
```

**Comment by ocefpaf** [comment]
> Ouch, on OSX:

```
 cp /Users/travis/miniconda3/conda-bld/work/lib/mpl_toolkits/basemap/data/countries_i.dat /Users/travis/miniconda3/conda-bld/work/lib/mpl_toolkits/basemap/data/countriesmeta_i.dat /Users/travis/miniconda3/conda-bld/work/lib/mpl_toolkits/basemap/data/gshhs_i.dat /Users/travis/miniconda3/conda-bld/work/lib/mpl_toolkits/basemap/data/gshhsmeta_i.dat /Users/travis/miniconda3/conda-bld/work/lib/mpl_toolkits/basemap/data/rivers_i.dat /Users/travis/miniconda3/conda-bld/work/lib/mpl_toolkits/basemap/data/riversmeta_i.dat /Users/travis/miniconda3/conda-bld/work/lib/mpl_toolkits/basemap/data/states_i.dat /Users/travis/miniconda3/conda-bld/work/lib/mpl_toolkits/basemap/data/statesmeta_i.dat /Users/travis/miniconda3/envs/_build/share/basemap
usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
       cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
Command failed: /bin/bash -x -e /Users/travis/build/conda-forge/basemap-data-hires-feedstock/recipe/build.sh
```

It was working berfore :cry:

**Comment by ocefpaf** [comment]
Travis issue might be the same as Windows+Python3 I had before and just now I get it! Conda is installing the default channel basemap instead of the latest one (ours) with the data directory.

**Comment by ocefpaf** [comment]
The bad version resolution is biting us here:

```
running run_test.py
Traceback (most recent call last):
  File "/Users/travis/miniconda3/conda-bld/test-tmp_dir/run_test.py", line 36, in <module>
    m.drawcounties()
  File "/Users/travis/miniconda3/envs/_test/lib/python3.5/site-packages/mpl_toolkits/basemap/__init__.py", line 1980, in drawcounties
    default_encoding='latin-1',drawbounds=drawbounds)
  File "/Users/travis/miniconda3/envs/_test/lib/python3.5/site-packages/mpl_toolkits/basemap/__init__.py", line 2146, in readshapefile
    for shprec in shf.shapeRecords():
  File "/Users/travis/miniconda3/envs/_test/lib/python3.5/site-packages/mpl_toolkits/basemap/shapefile.py", line 543, in shapeRecords
    for rec in zip(self.shapes(), self.records())]
  File "/Users/travis/miniconda3/envs/_test/lib/python3.5/site-packages/mpl_toolkits/basemap/shapefile.py", line 515, in records
    r = self.__record()
  File "/Users/travis/miniconda3/envs/_test/lib/python3.5/site-packages/mpl_toolkits/basemap/shapefile.py", line 491, in __record
    value = u(value)
  File "/Users/travis/miniconda3/envs/_test/lib/python3.5/site-packages/mpl_toolkits/basemap/shapefile.py", line 58, in u
    return v.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 2: invalid continuation byte
TESTS FAILED: basemap-data-hires-1.0.8.dev-0
```

That test is being run against basemap 1.0.7 and not 1.0.8.dev.

**Comment by pelson** [comment]
This is a great start. We will have to iterate if there are any issues. :+1:

**Pull request merged**
